; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define GTKPATH "C:\msys64\mingw64\"
#define SITE "https://slovesnov.rf.gd"
#define APPNAME "imageviewer"
#define VERSION "1.0.4"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{40197200-87CA-4FE1-801C-2506DF51EBA2}
;version number appears three times AppName shows application name in installer
AppName={#APPNAME}
AppVersion={#VERSION}
AppPublisher=Alexey Slovesnov
AppPublisherURL={#SITE}?{#APPNAME}
AppSupportURL={#SITE}?{#APPNAME}
AppUpdatesURL={#SITE}?{#APPNAME}
DefaultDirName={commonpf}\{#APPNAME}
;user can select setup folder
DisableDirPage=no
DefaultGroupName={#APPNAME}
OutputBaseFilename={#APPNAME}{#VERSION}Setup
SetupIconFile={#APPNAME}\icon\app.ico
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Messages]
english.BeveledLabel=English
russian.BeveledLabel=Russian

[Files]
#define i

#dim Icons[3]
#define Icons[0] "pan-up-symbolic"
#define Icons[1] "pan-down-symbolic"
#define Icons[2] "pan-end-symbolic"

#sub IconEntry
Source: "{#GTKPATH}share\icons\Adwaita\symbolic\ui\{#Icons[i]}.svg"; DestDir: "{app}\share\icons\Adwaita\symbolic\ui"; Flags: ignoreversion
#endsub
#for {i = 0; i < DimOf(Icons); i++} IconEntry

;generated by dll.sh
#dim Files[45]
#define Files[0] "libLerc"
#define Files[1] "libatk-1.0-0"
#define Files[2] "libbrotlicommon"
#define Files[3] "libbrotlidec"
#define Files[4] "libbz2-1"
#define Files[5] "libcairo-2"
#define Files[6] "libcairo-gobject-2"
#define Files[7] "libdatrie-1"
#define Files[8] "libdeflate"
#define Files[9] "libepoxy-0"
#define Files[10] "libexpat-1"
#define Files[11] "libffi-8"
#define Files[12] "libfontconfig-1"
#define Files[13] "libfreetype-6"
#define Files[14] "libfribidi-0"
#define Files[15] "libgcc_s_seh-1"
#define Files[16] "libgdk-3-0"
#define Files[17] "libgdk_pixbuf-2.0-0"
#define Files[18] "libgio-2.0-0"
#define Files[19] "libglib-2.0-0"
#define Files[20] "libgmodule-2.0-0"
#define Files[21] "libgobject-2.0-0"
#define Files[22] "libgraphite2"
#define Files[23] "libgtk-3-0"
#define Files[24] "libharfbuzz-0"
#define Files[25] "libiconv-2"
#define Files[26] "libintl-8"
#define Files[27] "libjbig-0"
#define Files[28] "libjpeg-8"
#define Files[29] "liblzma-5"
#define Files[30] "libpango-1.0-0"
#define Files[31] "libpangocairo-1.0-0"
#define Files[32] "libpangoft2-1.0-0"
#define Files[33] "libpangowin32-1.0-0"
#define Files[34] "libpcre2-8-0"
#define Files[35] "libpixman-1-0"
#define Files[36] "libpng16-16"
#define Files[37] "libsharpyuv-0"
#define Files[38] "libstdc++-6"
#define Files[39] "libthai-0"
#define Files[40] "libtiff-6"
#define Files[41] "libwebp-7"
#define Files[42] "libwinpthread-1"
#define Files[43] "libzstd"
#define Files[44] "zlib1"

#sub FilesEntry
Source: "{#GTKPATH}bin\{#Files[i]}.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
#endsub
#for {i = 0; i < DimOf(Files); i++} FilesEntry

Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders.cache"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0"; Flags: ignoreversion
Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders\*.dll"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0\loaders"; Flags: ignoreversion
Source: "{#GTKPATH}share\glib-2.0\schemas\gschemas.compiled"; DestDir: "{app}\share\glib-2.0\schemas"; Flags: ignoreversion

Source: "{#APPNAME}.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "*.css"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#APPNAME}\images\*"; Excludes: "*.txt"; DestDir: "{app}\bin\{#APPNAME}\images"; Flags: onlyifdoesntexist
Source: "{#APPNAME}\en\*"; DestDir: "{app}\bin\{#APPNAME}\en"; Flags: ignoreversion
Source: "{#APPNAME}\ru\*"; DestDir: "{app}\bin\{#APPNAME}\ru"; Flags: ignoreversion

[Icons]
Name: "{group}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{commondesktop}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{group}\{cm:UninstallProgram,{#APPNAME}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\bin\{#APPNAME}.exe"; Description: "{cm:LaunchProgram,{#APPNAME}}"; Flags: nowait postinstall skipifsilent

[CustomMessages]
english.checkUncheckAll=check/uncheck all
russian.checkUncheckAll=установить/снять все флажки
english.associate=associate a file extension with imageviewer
russian.associate=ассоциировать расширение файла с программой просмотра изображений
;https://stackoverflow.com/questions/8909283/inno-setup-optional-user-selectable-file-association 
;https://jrsoftware.org/ishelp/index.php?topic=taskssection
[Tasks]
Name: group; Description:{cm:checkUncheckAll}; GroupDescription: {cm:associate}; Flags: unchecked
Name: g\t0; Description: "*.ani"; Flags: unchecked
Name: g\t1; Description: "*.apm"; Flags: unchecked
Name: g\t2; Description: "*.bmp"; Flags: unchecked
Name: g\t3; Description: "*.cur"; Flags: unchecked
Name: g\t4; Description: "*.emf"; Flags: unchecked
Name: g\t5; Description: "*.gif"; Flags: unchecked
Name: g\t6; Description: "*.icns"; Flags: unchecked
Name: g\t7; Description: "*.ico"; Flags: unchecked
Name: g\t8; Description: "*.jpe"; Flags: unchecked
Name: g\t9; Description: "*.jpeg"; Flags: unchecked
Name: g\t10; Description: "*.jpg"; Flags: unchecked
Name: g\t11; Description: "*.pbm"; Flags: unchecked
Name: g\t12; Description: "*.pgm"; Flags: unchecked
Name: g\t13; Description: "*.png"; Flags: unchecked
Name: g\t14; Description: "*.pnm"; Flags: unchecked
Name: g\t15; Description: "*.ppm"; Flags: unchecked
Name: g\t16; Description: "*.qif"; Flags: unchecked
Name: g\t17; Description: "*.qtif"; Flags: unchecked
Name: g\t18; Description: "*.svg"; Flags: unchecked
Name: g\t19; Description: "*.svg.gz"; Flags: unchecked
Name: g\t20; Description: "*.svgz"; Flags: unchecked
Name: g\t21; Description: "*.targa"; Flags: unchecked
Name: g\t22; Description: "*.tga"; Flags: unchecked
Name: g\t23; Description: "*.tif"; Flags: unchecked
Name: g\t24; Description: "*.tiff"; Flags: unchecked
Name: g\t25; Description: "*.webp"; Flags: unchecked
Name: g\t26; Description: "*.wmf"; Flags: unchecked
Name: g\t27; Description: "*.xbm"; Flags: unchecked
Name: g\t28; Description: "*.xpm"; Flags: unchecked

[Registry]
Root: HKCR; Subkey: ".ani"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t0
Root: HKCR; Subkey: ".apm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t1
Root: HKCR; Subkey: ".bmp"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t2
Root: HKCR; Subkey: ".cur"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t3
Root: HKCR; Subkey: ".emf"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t4
Root: HKCR; Subkey: ".gif"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t5
Root: HKCR; Subkey: ".icns"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t6
Root: HKCR; Subkey: ".ico"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t7
Root: HKCR; Subkey: ".jpe"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t8
Root: HKCR; Subkey: ".jpeg"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t9
Root: HKCR; Subkey: ".jpg"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t10
Root: HKCR; Subkey: ".pbm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t11
Root: HKCR; Subkey: ".pgm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t12
Root: HKCR; Subkey: ".png"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t13
Root: HKCR; Subkey: ".pnm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t14
Root: HKCR; Subkey: ".ppm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t15
Root: HKCR; Subkey: ".qif"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t16
Root: HKCR; Subkey: ".qtif"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t17
Root: HKCR; Subkey: ".svg"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t18
Root: HKCR; Subkey: ".svg.gz"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t19
Root: HKCR; Subkey: ".svgz"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t20
Root: HKCR; Subkey: ".targa"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t21
Root: HKCR; Subkey: ".tga"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t22
Root: HKCR; Subkey: ".tif"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t23
Root: HKCR; Subkey: ".tiff"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t24
Root: HKCR; Subkey: ".webp"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t25
Root: HKCR; Subkey: ".wmf"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t26
Root: HKCR; Subkey: ".xbm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t27
Root: HKCR; Subkey: ".xpm"; ValueType: string; ValueName: ""; ValueData: "{#APPNAME}"; Flags: uninsdeletevalue; Tasks: g\t28
Root: HKCR; Subkey: {#APPNAME}; ValueType: string; ValueName: ""; ValueData: {#APPNAME}; Flags: uninsdeletekey; Tasks:g\t0 or g\t1 or g\t2 or g\t3 or g\t4 or g\t5 or g\t6 or g\t7 or g\t8 or g\t9 or g\t10 or g\t11 or g\t12 or g\t13 or g\t14 or g\t15 or g\t16 or g\t17 or g\t18 or g\t19 or g\t20 or g\t21 or g\t22 or g\t23 or g\t24 or g\t25 or g\t26 or g\t27 or g\t28
Root: HKCR; Subkey: "{#APPNAME}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\{#APPNAME}.exe,0"; Tasks:g\t0 or g\t1 or g\t2 or g\t3 or g\t4 or g\t5 or g\t6 or g\t7 or g\t8 or g\t9 or g\t10 or g\t11 or g\t12 or g\t13 or g\t14 or g\t15 or g\t16 or g\t17 or g\t18 or g\t19 or g\t20 or g\t21 or g\t22 or g\t23 or g\t24 or g\t25 or g\t26 or g\t27 or g\t28
Root: HKCR; Subkey: "{#APPNAME}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\{#APPNAME}.exe"" ""%1"""; Tasks:g\t0 or g\t1 or g\t2 or g\t3 or g\t4 or g\t5 or g\t6 or g\t7 or g\t8 or g\t9 or g\t10 or g\t11 or g\t12 or g\t13 or g\t14 or g\t15 or g\t16 or g\t17 or g\t18 or g\t19 or g\t20 or g\t21 or g\t22 or g\t23 or g\t24 or g\t25 or g\t26 or g\t27 or g\t28
