/*
 * enums.h
 *
 *  Created on: 03.04.2024
 *      Author: alexey slovesnov
 * copyright(c/c++): 2014-doomsday
 *           E-mail: slovesnov@yandex.ru
 *         homepage: slovesnov.users.sourceforge.net
 */

#ifndef ENUMS_H_
#define ENUMS_H_

enum class LANGUAGE {
	IMAGE_VIEWER,
	NO_IMAGE_HELP,
	RECURSIVE_DIRECTORY,
	LANGUAGE,
	WARN_BEFORE_SAVING_A_FILE,
	WARN_BEFORE_DELETING_A_FILE,
	REMOVE_FILE_OPTION,
	SHOW_POPUP_TIPS,
	REMOVE_FILES_TO_RECYCLE_BIN,
	REMOVE_FILES_PERMANENTLY,
	FILE,
	SAVE,
	RENAME,
	SCALED,
	ZOOM_FACTOR,
	SIZE,
	READABLE_FORMATS,
	READABLE_EXTENSIONS,
	WRITABLE_FORMATS,
	WRITABLE_EXTENSIONS, //should goes after WRITABLE_FORMATS
	HOMEPAGE,
	HOMEPAGE1,
	AUTHOR,
	AUTHOR1,
	EMAIL,
	EMAIL1,
	REMEMBER_THE_LAST_OPEN_DIRECTORY,
	VERSION,
	YES,
	NO,
	OK,
	CANCEL,
	RESET,
	JAN,
	FEB,
	MAR,
	APR,
	MAY,
	JUN,
	JUL,
	AUG,
	SEP,
	OCT,
	NOV,
	DEC,
	OPEN,
	OPEN_FILE,
	SELECT,
	QUESTION,
	ERROR,
	CANNOT_SAVE_FILE,
	DO_YOU_REALLY_WANT_TO_DELETE_THE_IMAGE,
	DO_YOU_REALLY_WANT_TO_SAVE_THE_IMAGE,
	SAVE_ERROR_MESSAGE,
	ZOOM,
	BYTES,
	KILOBYTES,
	MEGABYTES,
	AVERAGE,
	TOTAL,
	ONE_APPLICATION_INSTANCE,
	REQUIRES_RESTARTING,
	OPTIONS,
	KEYS,
	ABOUT,
	CLICK_TO_SET_THE_KEY,
	PRESS_ANY_KEY,
	HELP_TAB2,
	SHOW_THE_TOOLBAR_IN_FULLSCREEN_MODE,
	KEY_ALREADY_IN_USE,
	TOOLTIP1
//other toolitps
};

//if add TOOLBAR_INDEX enum need also add toopltip TOOLTIP.. also need change Frame::keyPress
enum class TOOLBAR_INDEX {
	ZOOM_IN,
	ZOOM_OUT,
	MODE_ZOOM_ANY,
	MODE_ZOOM_100,
	MODE_ZOOM_FIT,
	MODE_LIST,
	ROTATE_ANTICLOCKWISE,
	ROTATE_180,
	ROTATE_CLOCKWISE,
	FLIP_HORIZONTAL,
	FLIP_VERTICAL,
	HOME,
	PAGE_UP,
	PREVIOUS,
	NEXT,
	PAGE_DOWN,
	END,
	OPEN,
	DELETE_FILE,
	SAVE_FILE,
	REORDER_FILE,
	FULLSCREEN,
	SETTINGS,
	SZ
};

enum class ENUM_CONFIG_TAGS {
	VERSION,
	MODE,
	ORDER,
	LIST_ICON_INDEX,
	LANGUAGE,
	ASK_BEFORE_DELETE,
	DELETE_OPTION,
	ASK_BEFORE_SAVE,
	SHOW_POPUP,
	ONE_APPLICATION_INSTANCE,
	REMEMBER_THE_LAST_OPEN_DIRECTORY,
	SHOW_THE_TOOLBAR_IN_FULLSCREEN_MODE,
	LAST_OPEN_DIRECTORY, //not show in options
	KEYS, //not show in options
	RECURSIVE,
	SAVE_RENAME,

	ZOOM_FACTOR
};

enum COL {
	PIXBUF, TEXT
};

enum class MODE {
	ANY, NORMAL, FIT, LIST
};

enum class DIALOG {
	HELP, SETTINGS, DELETE, SAVE, ERROR
};

enum class TIMER {
	DIRECTORY, SZ
};

enum class LOAD_STATUS {
	NOT_LOADED, LOADED_OK, LOADED_ERROR
};

#endif /* ENUMS_H_ */
